### ISSUE TITLE
Ignore changed lines where the only difference is whitespace?

### ISSUE THREAD

**Issue by mickyscreggs** [kaishuoy/Marker#1]
Just a suggestion. Quite often the diff output is full of empty lines, which makes trying to find the actual code that the students have written a bit more annoying. I suspect it might be from students using some auto format thing and tabs getting changed to spaces or something.

**Comment by kaishuoy** [comment]
Do you have two files that cause this when diff'd? I think I know what youre talking about(long page full of >> << on alternating lines?) I cant find a file that generates it for me right now but I think i have seen this before

**Comment by kaishuoy** [comment]
Fixed now, closing
